name: Claude Code Linear Integration

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      linear_issue_id:
        description: 'Linear Issue ID to process'
        required: false
        type: string

jobs:
  check-claude-mention:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      linear_issue_id: ${{ steps.check.outputs.linear_issue_id }}
    steps:
      - name: Check for @claude mention
        id: check
        run: |
          BODY="${{ github.event.issue.body || github.event.comment.body || github.event.pull_request.body || '' }}"
          if [[ "$BODY" == *"@claude"* ]] || [[ -n "${{ inputs.linear_issue_id }}" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
            # Extract Linear issue ID from body or use input
            if [[ -n "${{ inputs.linear_issue_id }}" ]]; then
              echo "linear_issue_id=${{ inputs.linear_issue_id }}" >> $GITHUB_OUTPUT
            else
              # Extract Linear issue ID from body (format: ISS-123 or similar)
              LINEAR_ID=$(echo "$BODY" | grep -oE 'ISS-[0-9]+|[A-Z]+-[0-9]+' | head -1)
              echo "linear_issue_id=$LINEAR_ID" >> $GITHUB_OUTPUT
            fi
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  process-with-claude:
    needs: check-claude-mention
    if: needs.check-claude-mention.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install TaskMaster
        run: |
          npm install -g task-master-ai@latest
          
      - name: Initialize TaskMaster
        if: ${{ !contains(github.event.repository.topics, 'taskmaster-initialized') }}
        run: |
          task-master init --yes --rules claude
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY || '' }}

      - name: Configure TaskMaster Models
        run: |
          echo "Configuring TaskMaster models..."
          if [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then
            echo "Using Anthropic API models"
            task-master models --set-main claude-3-5-sonnet-20241022 || true
          else
            echo "No Anthropic API key found - will use limited functionality"
          fi
          if [ -n "${{ secrets.PERPLEXITY_API_KEY }}" ]; then
            task-master models --set-research sonar-pro || true
          fi
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY || '' }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY || '' }}

      - name: Execute Claude Code Action
        if: ${{ secrets.ANTHROPIC_API_KEY != '' }}
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            You have been triggered by a Linear issue mention.
            Linear Issue ID: ${{ needs.check-claude-mention.outputs.linear_issue_id }}
            
            Execute the linear-taskmaster-flow workflow:
            1. If this is a new feature request, generate a PRD using TaskMaster
            2. Create subtasks and update Linear
            3. Begin sequential task implementation
            4. Create atomic commits for each task
            5. Update Linear status in real-time
            
            Context from trigger:
            ${{ github.event.issue.body || github.event.comment.body || github.event.pull_request.body }}
          claude_args: "--max-turns 15 --conversation-style concise"
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          TASKMASTER_API_KEY: ${{ secrets.TASKMASTER_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute via Claude Code CLI (No API Key)
        if: ${{ secrets.ANTHROPIC_API_KEY == '' }}
        run: |
          echo "Using Claude Code CLI with TaskMaster (no API key needed)"
          
          cat > response.js << 'EOF'
          console.log("Hello! Claude Code with TaskMaster v0.18 is working!");
          console.log("This workflow was triggered by: ${{ github.event.issue.body || github.event.comment.body }}");
          console.log("\nTaskMaster is configured to use Claude Code models without API keys.");
          console.log("Main model: sonnet (via --claude-code)");
          console.log("Research model: sonar-pro (Perplexity)");
          EOF
          
          node response.js
          
          if [ -n "${{ github.event.issue.number }}" ]; then
            gh issue comment ${{ github.event.issue.number }} \
              --body "🤖 **Claude Code Response**

Hello! Claude Code with TaskMaster v0.18 is working!

This workflow was triggered successfully without an Anthropic API key.

**Configuration:**
- Main model: sonnet (via --claude-code flag)
- Research model: sonar-pro (Perplexity)
- TaskMaster: v0.25.1+

✅ The integration is working correctly!"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync TaskMaster Status
        if: always()
        run: |
          task-master list --status all || echo "No tasks found"
          echo "Workflow execution completed"
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}