name: Shared Secrets Workflow
# This is a reusable workflow that provides secrets to other repos

on:
  workflow_call:
    secrets:
      LINEAR_API_KEY:
        required: true
      ANTHROPIC_API_KEY:
        required: false
      PERPLEXITY_API_KEY:
        required: false

jobs:
  process-with-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Process the Linear integration request
          claude_args: "--max-turns 15 --conversation-style concise"
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}