name: Test Simple Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: echo "Test workflow triggered!"